# Generated by Django 3.2.5 on 2021-07-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_produit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
