# Generated by Django 3.2.5 on 2021-08-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_produit_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nom',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='produit',
            name='picture',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('Composant électronique', 'Composant électronique'), ('Plastique', 'Plastique'), ('Ordinateur bureautique', 'Ordinateur bureautique'), ('Ordinateur portable', 'Ordinateur portable'), ('Ustensile de cuisine', 'Ustensile de cuisine'), ('Aliments', 'Aliments'), ('Matériel de construction', 'Matériel de construction'), ('Moyen de transport', 'Moyen de transport')], max_length=100, null=True),
        ),
    ]
