# Generated by Django 3.2.5 on 2021-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_auto_20210727_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('En_instance', 'En instance'), ('Livre', 'Livré'), ('Non_livré', 'Non livré')], max_length=200, null=True),
        ),
    ]
