# Generated by Django 3.2.5 on 2021-07-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_alter_commande_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('En instance', 'En instance'), ('Livré', 'Livré'), ('Non livré', 'Non livré')], max_length=200, null=True),
        ),
    ]
